### PR TITLE
intel-graphics-compiler: LLVM 13 fixes

### LINKED ISSUE #3: intel-graphics-compiler 1.0.8365 in current master doesn't build against llvm 13 in meta-clang master
Some errors:
```
| In file included from /data/dtd-yocto-3.4/tmp-sicom-glibc/work/x86_64-linux/intel-graphics-compiler-native/1.0.8365-r0/git/IGC/LLVM3DBuilder/BuiltinsFrontend.hpp:860,
|                  from /data/dtd-yocto-3.4/tmp-sicom-glibc/work/x86_64-linux/intel-graphics-compiler-native/1.0.8365-r0/git/IGC/Compiler/LegalizationPass.cpp:29:
| /data/dtd-yocto-3.4/tmp-sicom-glibc/work/x86_64-linux/intel-graphics-compiler-native/1.0.8365-r0/git/IGC/LLVM3DBuilder/BuiltinsFrontendDefinitions.hpp: In member function ‘llvm::Value* LLVM3DBuilder<preserveNames, T, InserterTy>::ScalarsToVector(llvm::Value* (&)[4], unsigned int)’:
| /data/dtd-yocto-3.4/tmp-sicom-glibc/work/x86_64-linux/intel-graphics-compiler-native/1.0.8365-r0/git/IGC/LLVM3DBuilder/BuiltinsFrontendDefinitions.hpp:5031:72: error: ‘class llvm::VectorType’ has no member named ‘getNumElements’; did you mean ‘getArrayNumElements’?
|  5031 |     for (unsigned i = 0; i < llvm::cast<llvm::VectorType>(resultType)->getNumElements(); i++)
|       |                                                                        ^~~~~~~~~~~~~~
|       |                                                                        getArrayNumElements
```
and
```
| /data/dtd-yocto-3.4/tmp-sicom-glibc/work/x86_64-linux/intel-graphics-compiler-native/1.0.8365-r0/git/IGC/Compiler/HandleLoadStoreInstructions.cpp: In member function ‘void IGC::HandleLoadStoreInstructions::visitLoadInst(llvm::LoadInst&)’:
| /data/dtd-yocto-3.4/tmp-sicom-glibc/work/x86_64-linux/intel-graphics-compiler-native/1.0.8365-r0/git/IGC/Compiler/HandleLoadStoreInstructions.cpp:103:53: error: ‘llvm::LoadInst* llvm::IRBuilderBase::CreateLoad(llvm::Value*, const llvm::Twine&)’ is deprecated: Use the version that explicitly specifies the loaded type instead [-Werror=deprecated-declarations]
|   103 |                 Value* data = builder.CreateLoad(i2p);
|       |                                                     ^
| In file included from /data/dtd-yocto-3.4/tmp-sicom-glibc/work/x86_64-linux/intel-graphics-compiler-native/1.0.8365-r0/recipe-sysroot-native/usr/include/llvm/Support/ErrorHandling.h:17,
|                  from /data/dtd-yocto-3.4/tmp-sicom-glibc/work/x86_64-linux/intel-graphics-compiler-native/1.0.8365-r0/recipe-sysroot-native/usr/include/llvm/ADT/Hashing.h:48,
|                  from /data/dtd-yocto-3.4/tmp-sicom-glibc/work/x86_64-linux/intel-graphics-compiler-native/1.0.8365-r0/recipe-sysroot-native/usr/include/llvm/ADT/Optional.h:18,
|                  from /data/dtd-yocto-3.4/tmp-sicom-glibc/work/x86_64-linux/intel-graphics-compiler-native/1.0.8365-r0/recipe-sysroot-native/usr/include/llvm/ADT/STLExtras.h:19,
|                  from /data/dtd-yocto-3.4/tmp-sicom-glibc/work/x86_64-linux/intel-graphics-compiler-native/1.0.8365-r0/recipe-sysroot-native/usr/include/llvm/ADT/StringRef.h:12,
|                  from /data/dtd-yocto-3.4/tmp-sicom-glibc/work/x86_64-linux/intel-graphics-compiler-native/1.0.8365-r0/recipe-sysroot-native/usr/include/llvm/IR/DiagnosticHandler.h:15,
|                  from /data/dtd-yocto-3.4/tmp-sicom-glibc/work/x86_64-linux/intel-graphics-compiler-native/1.0.8365-r0/recipe-sysroot-native/usr/include/llvm/IR/LLVMContext.h:18,
|                  from /data/dtd-yocto-3.4/tmp-sicom-glibc/work/x86_64-linux/intel-graphics-compiler-native/1.0.8365-r0/git/IGC/common/debug/Debug.hpp:12,
|                  from /data/dtd-yocto-3.4/tmp-sicom-glibc/work/x86_64-linux/intel-graphics-compiler-native/1.0.8365-r0/git/IGC/common/Types.hpp:16,
|                  from /data/dtd-yocto-3.4/tmp-sicom-glibc/work/x86_64-linux/intel-graphics-compiler-native/1.0.8365-r0/git/IGC/Compiler/CodeGenContextWrapper.hpp:11,
|                  from /data/dtd-yocto-3.4/tmp-sicom-glibc/work/x86_64-linux/intel-graphics-compiler-native/1.0.8365-r0/git/IGC/Compiler/HandleLoadStoreInstructions.hpp:11,
|                  from /data/dtd-yocto-3.4/tmp-sicom-glibc/work/x86_64-linux/intel-graphics-compiler-native/1.0.8365-r0/git/IGC/Compiler/HandleLoadStoreInstructions.cpp:9:
| /data/dtd-yocto-3.4/tmp-sicom-glibc/work/x86_64-linux/intel-graphics-compiler-native/1.0.8365-r0/recipe-sysroot-native/usr/include/llvm/IR/IRBuilder.h:1678:3: note: declared here
|  1678 |   LLVM_ATTRIBUTE_DEPRECATED(LoadInst *CreateLoad(Value *Ptr,
|       |   ^~~~~~~~~~~~~~~~~~~~~~~~~
| /data/dtd-yocto-3.4/tmp-sicom-glibc/work/x86_64-linux/intel-graphics-compiler-native/1.0.8365-r0/git/IGC/Compiler/HandleLoadStoreInstructions.cpp:115:56: error: ‘llvm::LoadInst* llvm::IRBuilderBase::CreateLoad(llvm::Value*, const llvm::Twine&)’ is deprecated: Use the version that explicitly specifies the loaded type instead [-Werror=deprecated-declarations]
|   115 |             Value* newLoad = builder.CreateLoad(newPtrv);
|       |                                                        ^
| In file included from /data/dtd-yocto-3.4/tmp-sicom-glibc/work/x86_64-linux/intel-graphics-compiler-native/1.0.8365-r0/recipe-sysroot-native/usr/include/llvm/Support/ErrorHandling.h:17,
|                  from /data/dtd-yocto-3.4/tmp-sicom-glibc/work/x86_64-linux/intel-graphics-compiler-native/1.0.8365-r0/recipe-sysroot-native/usr/include/llvm/ADT/Hashing.h:48,
|                  from /data/dtd-yocto-3.4/tmp-sicom-glibc/work/x86_64-linux/intel-graphics-compiler-native/1.0.8365-r0/recipe-sysroot-native/usr/include/llvm/ADT/Optional.h:18,
|                  from /data/dtd-yocto-3.4/tmp-sicom-glibc/work/x86_64-linux/intel-graphics-compiler-native/1.0.8365-r0/recipe-sysroot-native/usr/include/llvm/ADT/STLExtras.h:19,
|                  from /data/dtd-yocto-3.4/tmp-sicom-glibc/work/x86_64-linux/intel-graphics-compiler-native/1.0.8365-r0/recipe-sysroot-native/usr/include/llvm/ADT/StringRef.h:12,
|                  from /data/dtd-yocto-3.4/tmp-sicom-glibc/work/x86_64-linux/intel-graphics-compiler-native/1.0.8365-r0/recipe-sysroot-native/usr/include/llvm/IR/DiagnosticHandler.h:15,
|                  from /data/dtd-yocto-3.4/tmp-sicom-glibc/work/x86_64-linux/intel-graphics-compiler-native/1.0.8365-r0/recipe-sysroot-native/usr/include/llvm/IR/LLVMContext.h:18,
|                  from /data/dtd-yocto-3.4/tmp-sicom-glibc/work/x86_64-linux/intel-graphics-compiler-native/1.0.8365-r0/git/IGC/common/debug/Debug.hpp:12,
|                  from /data/dtd-yocto-3.4/tmp-sicom-glibc/work/x86_64-linux/intel-graphics-compiler-native/1.0.8365-r0/git/IGC/common/Types.hpp:16,
|                  from /data/dtd-yocto-3.4/tmp-sicom-glibc/work/x86_64-linux/intel-graphics-compiler-native/1.0.8365-r0/git/IGC/Compiler/CodeGenContextWrapper.hpp:11,
|                  from /data/dtd-yocto-3.4/tmp-sicom-glibc/work/x86_64-linux/intel-graphics-compiler-native/1.0.8365-r0/git/IGC/Compiler/HandleLoadStoreInstructions.hpp:11,
|                  from /data/dtd-yocto-3.4/tmp-sicom-glibc/work/x86_64-linux/intel-graphics-compiler-native/1.0.8365-r0/git/IGC/Compiler/HandleLoadStoreInstructions.cpp:9:
| /data/dtd-yocto-3.4/tmp-sicom-glibc/work/x86_64-linux/intel-graphics-compiler-native/1.0.8365-r0/recipe-sysroot-native/usr/include/llvm/IR/IRBuilder.h:1678:3: note: declared here
|  1678 |   LLVM_ATTRIBUTE_DEPRECATED(LoadInst *CreateLoad(Value *Ptr,
|       |   ^~~~~~~~~~~~~~~~~~~~~~~~~
| cc1plus: all warnings being treated as errors
```
and
```
| /data/dtd-yocto-3.4/tmp-sicom-glibc/work/x86_64-linux/intel-graphics-compiler-native/1.0.8365-r0/git/IGC/Compiler/GenTTI.cpp: In member function ‘int llvm::GenIntrinsicsTTIImpl::getUserCost(const llvm::User*, llvm::ArrayRef<const llvm::Value*>, llvm::TargetTransformInfo::TargetCostKind)’:
| /data/dtd-yocto-3.4/tmp-sicom-glibc/work/x86_64-linux/intel-graphics-compiler-native/1.0.8365-r0/git/IGC/Compiler/GenTTI.cpp:486:32: error: cannot convert ‘llvm::InstructionCost’ to ‘int’ in return
|   486 |       return BaseT::getUserCost(U, Operands, CostKind);
|       |              ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
|       |                                |
|       |                                llvm::InstructionCost
```
and
```
| /data/dtd-yocto-3.4/tmp-sicom-glibc/work/x86_64-linux/intel-graphics-compiler-native/1.0.8365-r0/git/IGC/Compiler/PromoteResourceToDirectAS.cpp: In member function ‘void IGC::PromoteResourceToDirectAS::PromoteBufferToDirectAS(llvm::Instruction*, llvm::Value*)’:
| /data/dtd-yocto-3.4/tmp-sicom-glibc/work/x86_64-linux/intel-graphics-compiler-native/1.0.8365-r0/git/IGC/Compiler/PromoteResourceToDirectAS.cpp:623:40: error: ‘llvm::LoadInst* llvm::IRBuilderBase::CreateAlignedLoad(llvm::Value*, llvm::MaybeAlign, bool, const llvm::Twine&)’ is deprecated: Use the version that explicitly specifies the loaded type instead [-Werror=deprecated-declarations]
|   623 |                 ldRawIntr->isVolatile());
|       |                                        ^
| In file included from /data/dtd-yocto-3.4/tmp-sicom-glibc/work/x86_64-linux/intel-graphics-compiler-native/1.0.8365-r0/recipe-sysroot-native/usr/include/llvm/Support/ErrorHandling.h:17,
|                  from /data/dtd-yocto-3.4/tmp-sicom-glibc/work/x86_64-linux/intel-graphics-compiler-native/1.0.8365-r0/recipe-sysroot-native/usr/include/llvm/ADT/Hashing.h:48,
|                  from /data/dtd-yocto-3.4/tmp-sicom-glibc/work/x86_64-linux/intel-graphics-compiler-native/1.0.8365-r0/recipe-sysroot-native/usr/include/llvm/ADT/Optional.h:18,
|                  from /data/dtd-yocto-3.4/tmp-sicom-glibc/work/x86_64-linux/intel-graphics-compiler-native/1.0.8365-r0/recipe-sysroot-native/usr/include/llvm/ADT/STLExtras.h:19,
|                  from /data/dtd-yocto-3.4/tmp-sicom-glibc/work/x86_64-linux/intel-graphics-compiler-native/1.0.8365-r0/recipe-sysroot-native/usr/include/llvm/PassAnalysisSupport.h:25,
|                  from /data/dtd-yocto-3.4/tmp-sicom-glibc/work/x86_64-linux/intel-graphics-compiler-native/1.0.8365-r0/recipe-sysroot-native/usr/include/llvm/Pass.h:337,
|                  from /data/dtd-yocto-3.4/tmp-sicom-glibc/work/x86_64-linux/intel-graphics-compiler-native/1.0.8365-r0/git/IGC/Compiler/PromoteResourceToDirectAS.h:12,
|                  from /data/dtd-yocto-3.4/tmp-sicom-glibc/work/x86_64-linux/intel-graphics-compiler-native/1.0.8365-r0/git/IGC/Compiler/PromoteResourceToDirectAS.cpp:9:
| /data/dtd-yocto-3.4/tmp-sicom-glibc/work/x86_64-linux/intel-graphics-compiler-native/1.0.8365-r0/recipe-sysroot-native/usr/include/llvm/IR/IRBuilder.h:1737:3: note: declared here
|  1737 |   LLVM_ATTRIBUTE_DEPRECATED(LoadInst *CreateAlignedLoad(Value *Ptr,
|       |   ^~~~~~~~~~~~~~~~~~~~~~~~~
| cc1plus: all warnings being treated as errors
```

### PR DESCRIPTION
**Pull request by zboszor**
Also add CXXFLAGS=-Wno-error=deprecated-declarations, to turn
some deprecated LLVM API usage from warnings to errors.

Signed-off-by: Zoltán Böszörményi <zboszor@gmail.com>

Fixes #3

### CODE REVIEW

**Comment by kraj** [comment]
looks good. I have forwarded it to meta-intel upstream directly. If its not accepted we will apply it to our fork.

**Comment by zboszor** [comment]
> looks good. I have forwarded it to meta-intel upstream directly. If its not accepted we will apply it to our fork.

I sent it to the proper mailing list but in the meantime it turned out it's not enough to get everything build with LLVM 13.
`opencl-clang` needs a version 13.0.0 recipe from the `ocl-open-130` branch, which in turn seems to need https://github.com/intel/opencl-clang/pull/273
I will experiment further on Monday.

**Comment by zboszor** [comment]
The new IGC version seems to need  more recipe changes, it fails in `do_configure` :(

**Comment by zboszor** [comment]
The new IGC version now compiles but still fails to build intel-compute-runtime with LLVM 13

**Comment by kraj** [comment]
I am carrying https://github.com/YoeDistro/meta-intel/commit/f36dea1c17b75b3245694582efff96a00b4d6ffd in `yoe/mut` do we still need this ?

**Comment by zboszor** [comment]
> I am carrying [f36dea1](https://github.com/YoeDistro/meta-intel/commit/f36dea1c17b75b3245694582efff96a00b4d6ffd) in `yoe/mut` do we still need this ?

It was an experiment on my side, still fails to build. I abandoned this PR and let the Intel guys to solve their stuff. They seem to be progressing.

**Comment by zboszor** [comment]
`ocloc` still crashes when run via qemuwrapper. Manual run shows this backtrace without source lines:
```
[0]: /data/dtd-yocto-3.4/tmp-sicom-glibc/work/corei7-64-oe-linux/intel-compute-runtime/21.36.20889-r0/build/bin/libocloc.so(+0x7f3f0) [0x40018bb3f0]
[1]: /data/dtd-yocto-3.4/tmp-sicom-glibc/work/corei7-64-oe-linux/intel-compute-runtime/21.36.20889-r0/recipe-sysroot/usr/lib/libc.so.6(+0x41930) [0x400193e930]
[2]: /data/dtd-yocto-3.4/tmp-sicom-glibc/work/corei7-64-oe-linux/intel-compute-runtime/21.36.20889-r0/recipe-sysroot/usr/lib/libLLVM-13.so(_ZN4llvm11PointerType3getEPNS_4TypeEj+0x20) [0x40048009a0]
[3]: /data/dtd-yocto-3.4/tmp-sicom-glibc/work/corei7-64-oe-linux/intel-compute-runtime/21.36.20889-r0/recipe-sysroot/usr/lib/libigc.so.1(+0x2b20e5) [0x40020b90e5]
[4]: /data/dtd-yocto-3.4/tmp-sicom-glibc/work/corei7-64-oe-linux/intel-compute-runtime/21.36.20889-r0/recipe-sysroot/usr/lib/libigc.so.1(+0x2cf642) [0x40020d6642]
[5]: /data/dtd-yocto-3.4/tmp-sicom-glibc/work/corei7-64-oe-linux/intel-compute-runtime/21.36.20889-r0/recipe-sysroot/usr/lib/libigc.so.1(+0x2d2b11) [0x40020d9b11]
[6]: /data/dtd-yocto-3.4/tmp-sicom-glibc/work/corei7-64-oe-linux/intel-compute-runtime/21.36.20889-r0/recipe-sysroot/usr/lib/libigc.so.1(+0x2d8588) [0x40020df588]
[7]: /data/dtd-yocto-3.4/tmp-sicom-glibc/work/corei7-64-oe-linux/intel-compute-runtime/21.36.20889-r0/recipe-sysroot/usr/lib/libigc.so.1(+0x2ddf9f) [0x40020e4f9f]
[8]: /data/dtd-yocto-3.4/tmp-sicom-glibc/work/corei7-64-oe-linux/intel-compute-runtime/21.36.20889-r0/recipe-sysroot/usr/lib/libigc.so.1(+0x2dea98) [0x40020e5a98]
[9]: /data/dtd-yocto-3.4/tmp-sicom-glibc/work/corei7-64-oe-linux/intel-compute-runtime/21.36.20889-r0/recipe-sysroot/usr/lib/libigc.so.1(+0x219d78) [0x4002020d78]
[10]: /data/dtd-yocto-3.4/tmp-sicom-glibc/work/corei7-64-oe-linux/intel-compute-runtime/21.36.20889-r0/recipe-sysroot/usr/lib/libigc.so.1(+0x21cada) [0x4002023ada]
[11]: /data/dtd-yocto-3.4/tmp-sicom-glibc/work/corei7-64-oe-linux/intel-compute-runtime/21.36.20889-r0/recipe-sysroot/usr/lib/libigc.so.1(+0x21ddaa) [0x4002024daa]
[12]: /data/dtd-yocto-3.4/tmp-sicom-glibc/work/corei7-64-oe-linux/intel-compute-runtime/21.36.20889-r0/recipe-sysroot/usr/lib/libigc.so.1(+0x2ec6ee) [0x40020f36ee]
[13]: /data/dtd-yocto-3.4/tmp-sicom-glibc/work/corei7-64-oe-linux/intel-compute-runtime/21.36.20889-r0/recipe-sysroot/usr/lib/libigc.so.1(+0x2ed59f) [0x40020f459f]
[14]: /data/dtd-yocto-3.4/tmp-sicom-glibc/work/corei7-64-oe-linux/intel-compute-runtime/21.36.20889-r0/build/bin/libocloc.so(_ZN3NEO15OfflineCompiler15buildSourceCodeEv+0x23b) [0x400188e3db]
[15]: /data/dtd-yocto-3.4/tmp-sicom-glibc/work/corei7-64-oe-linux/intel-compute-runtime/21.36.20889-r0/build/bin/libocloc.so(_ZN3NEO15OfflineCompiler5buildEv+0x45) [0x4001892e15]
[16]: /data/dtd-yocto-3.4/tmp-sicom-glibc/work/corei7-64-oe-linux/intel-compute-runtime/21.36.20889-r0/build/bin/libocloc.so(+0x7f499) [0x40018bb499]
[17]: /data/dtd-yocto-3.4/tmp-sicom-glibc/work/corei7-64-oe-linux/intel-compute-runtime/21.36.20889-r0/build/bin/libocloc.so(_Z20buildWithSafetyGuardPN3NEO15OfflineCompilerE+0xba) [0x40018bb34a]
[18]: /data/dtd-yocto-3.4/tmp-sicom-glibc/work/corei7-64-oe-linux/intel-compute-runtime/21.36.20889-r0/build/bin/libocloc.so(oclocInvoke+0xc3b) [0x400187e5eb]
[19]: /data/dtd-yocto-3.4/tmp-sicom-glibc/work/corei7-64-oe-linux/intel-compute-runtime/21.36.20889-r0/build/bin/ocloc(main+0x23) [0x4000000753]
[20]: /data/dtd-yocto-3.4/tmp-sicom-glibc/work/corei7-64-oe-linux/intel-compute-runtime/21.36.20889-r0/recipe-sysroot/usr/lib/libc.so.6(+0x2d51b) [0x400192a51b]
[21]: /data/dtd-yocto-3.4/tmp-sicom-glibc/work/corei7-64-oe-linux/intel-compute-runtime/21.36.20889-r0/recipe-sysroot/usr/lib/libc.so.6(__libc_start_main+0x7c) [0x400192a5cc]
[22]: /data/dtd-yocto-3.4/tmp-sicom-glibc/work/corei7-64-oe-linux/intel-compute-runtime/21.36.20889-r0/build/bin/ocloc(_start+0x25) [0x4000000785]
```
Maybe a newer release/13.x is required in meta-clang? I saw two crash fixes there that may or may not fix the crash in compute-runtime. @kraj

**Pull request closed without merging**
